services:
  price_feeder:
    platform: linux/x86_64
    restart: always
    container_name: price_feeder
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    tty: true
